### ISSUE TITLE
Invalid TENANT environment variable

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [SabatinoMasala/multitenant-expo#1]
After setting up with "yarn"
and then start development with first tenant

"Invalid TENANT environment variable"

```
TENANT=tenant-1 yarn start
```

**Comment by NilsBaumgartner1994** [comment]
Change it to TENANT=first-tenant yarn start

**Comment by SabatinoMasala** [comment]
Ack! My bad, will change it, thanks for mentioning it!
